update flower image to working version
Since latest version seems to have an issue with python3.9, container built with the latest image would always die due to `ImportError: cannot import name 'Command' from 'celery.bin.base'`. Downgrading to 0.9.5 fixed the issue, with all tests passing.

Signed-off-by: ksdfg <ksdfg123@gmail.com>