api: professors: fix issue detected by mypy
app/api/api_v1/endpoints/professors.py:90: error: Item "None" of "Optional[Professor]" has no attribute "user_id"

We need to ensure that the user is indeed a professor, just an ID comparison isn't enough to give them a response

Signed-off-by: Akhil Narang <me@akhilnarang.dev>